<a href="https://colab.research.google.com/github/abhijeetrajhansgithub/GoogleColab/blob/main/TensorFlow-Learning/TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook, we are going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to Tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular python functions)
* Using GPUs with Tensorflow (or TPUs)

## Introduction to Tensors

In [150]:
# import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.15.0


In [151]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [152]:
# Check the number of dimensions of the tensor

scalar.ndim

0

In [153]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [154]:
vector.ndim

1

In [155]:
v2 = tf.constant([
    [1, 2],
    [3, 4]
])

v2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [156]:
v2.ndim

2

In [157]:
v3 = tf.constant(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [10, 20, 30],
            [40, 50, 60]
        ]
    ]
)

v3

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]], dtype=int32)>

In [158]:
v3.ndim

3

In [159]:
# Create a matrix

matrix = tf.constant(
    [
        [7, 10],
        [10, 7]
    ]
)

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]], dtype=int32)>

In [160]:
matrix.ndim

2

In [161]:
# Create another matrix

another_matrix = tf.constant([
    [10., 7., 3.],
    [4., 5., 12.],
    [17., 15., 20.]
])

another_matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[10.,  7.,  3.],
       [ 4.,  5., 12.],
       [17., 15., 20.]], dtype=float32)>

In [162]:
another_matrix.ndim

2

In [163]:
v4 = tf.constant([1, 2, 3], dtype=tf.float64)  # specify the datatype with dtype parameter

v4

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [164]:
# Let's create a tensor

tensor = tf.constant(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
        [
            [13, 14, 15],
            [16, 17, 18]
        ]
    ]
)

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [165]:
tensor.ndim

3

What we have created so far:
* Scalar: a single number
* Vector: a number with direction
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number)

### Another Way to Create a Tensor: `tf.Variable`

In [166]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [167]:
changeable_tensor = tf.Variable([10, 7])

unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [168]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [169]:
# .assign

changeable_tensor[0].assign(20)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([20,  7], dtype=int32)>

In [170]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([20,  7], dtype=int32)>

In [171]:
# Let's try to change the unchangeable tensor

# unchangeable_tensor[0].assign(7) -- error

### Creating Random Tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [172]:
random_1 = tf.random.Generator.from_seed(42)

random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [173]:
random_2 = tf.random.Generator.from_seed(42)

random_2_uniform = random_2.uniform(shape=(3, 4))  # uniform distribution
random_2_uniform

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.7493447 , 0.73561966, 0.45230794, 0.49039817],
       [0.1889317 , 0.52027524, 0.8736881 , 0.46921718],
       [0.63932586, 0.6467117 , 0.96246755, 0.41009164]], dtype=float32)>

In [174]:
random_2_normal = random_2.normal(shape=(3, 4))  # normal distribution
random_2_normal

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.2866228 , -0.7147561 , -0.1019548 ,  0.3831789 ],
       [-0.31881508, -0.3712327 , -0.2955993 ,  0.32111698],
       [ 1.077732  ,  0.2348518 ,  0.25318494,  0.36563298]],
      dtype=float32)>

In [175]:
# Define the parameters
num_trials = 10
probs = 0.8
shape = (4, 5)
seed = (42, 0)  # Seed for reproducibility

# Generating binomial random variables
random_2_binomial = tf.random.stateless_binomial(shape=shape, seed=seed, counts=num_trials, probs=probs)

random_2_binomial

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 8,  9,  8, 10, 10],
       [ 6,  8,  8,  9,  7],
       [ 7,  6,  7,  8,  8],
       [ 9,  8,  9,  6, 10]], dtype=int32)>

In [176]:
# Generating poisson random variables
random_2_poisson = tf.random.stateless_poisson(shape=(6, 4), seed=(42, 0), lam=5)

random_2_poisson

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 3, 10,  6,  4],
       [ 5,  5,  4,  3],
       [ 5,  6,  6,  6],
       [ 7,  4,  6,  2],
       [ 5,  4,  1,  4],
       [ 4,  5,  4,  5]], dtype=int32)>

### Shuffle the order of elements in a tensor

In [177]:
# Shuffle a tensor

not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5]
])

not_shuffled.ndim

2

In [178]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [179]:
# Shuffle the tensor with a seed
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled, seed=42)

shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [180]:
tf.random.shuffle(not_shuffled, seed=42)  # different order each time

# hence this is an operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [181]:
tf.ones(shape=(2, 3), dtype=tf.int64)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [182]:
tf.zeros(shape=(7, 10), dtype=tf.float64)

<tf.Tensor: shape=(7, 10), dtype=float64, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])>

### Turn NumPy arrays into tensors

In [183]:
# You can also turn NumPy arrays into TensorFlow tensors

import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)

numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [184]:
tensor_A = tf.constant(numpy_A)

tensor_A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [185]:
# back to NumPy array

numpy_back = tensor_A.numpy()

numpy_back

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [186]:
B = tf.constant(numpy_A, shape=(2, 3, 4))
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [187]:
reshape = tf.reshape(B, shape=(3, 8))
reshape

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [188]:
C = tf.constant(B, shape=(8, 3))
C  # also reshaped

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]], dtype=int32)>

In [189]:
C.ndim

2

### Getting information from tensors

When dealing with tensors we probably have to be aware of the followinf attributes:
* shape
* axis
* rank or dimension
* size

In [190]:
# Create a rank 4 tensor

rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [191]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [192]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [193]:
# Get various attributes of our tensor

print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank)L ", rank_4_tensor.ndim)
print("Shape of the tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements: ", tf.size(rank_4_tensor))
print("Total number of elements: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank)L  4
Shape of the tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements:  120


### Indexing and Expanding Tensors

In [194]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [195]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [196]:
rank_4_tensor[0, :2]

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [197]:
# get first element from each dimention except for the last one

rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [198]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [199]:
# Create a rank two tensor (2 dimensions)

tf.random.set_seed(42)

rank_2_tensor = tf.random.uniform(shape=(2, 2))

rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.6645621 , 0.44100678],
       [0.3528825 , 0.46448255]], dtype=float32)>

In [200]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [201]:
# Get the last item of each row of our rank 2 tensor

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.44100678, 0.46448255], dtype=float32)>

In [202]:
# Add in extra dimention to our rank 2 tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis]

rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.6645621 ],
        [0.44100678]],

       [[0.3528825 ],
        [0.46448255]]], dtype=float32)>

In [203]:
rank_3_tensor[1, 1]

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.46448255], dtype=float32)>

In [204]:
rank_2_tensor[1, 1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.46448255>

In [205]:
# Alternative to `tf.newaxis`

tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.6645621 ],
        [0.44100678]],

       [[0.3528825 ],
        [0.46448255]]], dtype=float32)>

In [206]:
# Adding two dimensions to the end of rank_2_tensor

rank_2_tensor[..., tf.newaxis][..., tf.newaxis]

<tf.Tensor: shape=(2, 2, 1, 1), dtype=float32, numpy=
array([[[[0.6645621 ]],

        [[0.44100678]]],


       [[[0.3528825 ]],

        [[0.46448255]]]], dtype=float32)>

In [207]:
rank_2_tensor, rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678],
        [0.3528825 , 0.46448255]], dtype=float32)>,
 2)

In [208]:
# Expand the 0-axis

tf.expand_dims(rank_2_tensor, axis=0), tf.expand_dims(rank_2_tensor, axis=0).ndim

(<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
 array([[[0.6645621 , 0.44100678],
         [0.3528825 , 0.46448255]]], dtype=float32)>,
 3)

### Manipulating Tensors (Tensor Operations)

**Basic Operations**

In [209]:
# You can add values to a tensor using the addition operator

tensor = tf.constant([[10, 7], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [210]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [211]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [212]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [213]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [214]:
# We can use the TensorFlow built-in functions

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [215]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [216]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [217]:
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [218]:
# Use cast to change the dtype of an existing tensor
tf.cast((tf.divide(tensor, 10)), dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 0]], dtype=int32)>

**Matrix Multiplication**

In [219]:
m1 = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

m1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [220]:
m2 = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

m2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [221]:
# Matrix multiplication in TensorFow

tf.linalg.matmul(m1, m2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]], dtype=int32)>

In [222]:
tf.linalg.matmul(m2, m2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]], dtype=int32)>

In [223]:
m2 * m2  # element-wise

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)>

In [224]:
# Matrix multiplication with Python operator "@"

m1 @ m2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]], dtype=int32)>

In [225]:
m2 @ m2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]], dtype=int32)>

In [226]:
m1.shape, m2.shape

(TensorShape([2, 3]), TensorShape([3, 3]))

In [227]:
# Create a (3, 2) tensor

X = tf.random.uniform(shape=(3, 2), minval = 0, maxval=20, dtype=tf.int64)
X

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 6,  3],
       [ 0, 16],
       [10,  9]])>

In [228]:
Y = tf.random.uniform(shape=(3, 2), minval = 0, maxval=20, dtype=tf.int64)
Y

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[16,  1],
       [15,  8],
       [ 4,  5]])>

In [229]:
X * Y

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 96,   3],
       [  0, 128],
       [ 40,  45]])>

In [230]:
tf.linalg.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[136,  56],
       [324, 176]])>

In [231]:
new_tensor = tf.random.uniform(dtype=tf.int64, minval=0, maxval=20, shape=(3, 2))
new_tensor

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[14,  8],
       [ 2,  4],
       [10, 11]])>

In [232]:
tf.reshape(new_tensor, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[14,  8,  2],
       [ 4, 10, 11]])>

In [233]:
X

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 6,  3],
       [ 0, 16],
       [10,  9]])>

In [234]:
# Matrix multipli  cation

tf.linalg.matmul(X, tf.reshape(new_tensor, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 96,  78,  45],
       [ 64, 160, 176],
       [176, 170, 119]])>

In [235]:
# How to use tf.transpose

A = tf.random.uniform(minval=0, maxval=100, dtype=tf.int64, shape=(3, 2))
A

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[ 9,  6],
       [ 1, 61],
       [68,  7]])>

In [236]:
A, tf.transpose(A), tf.reshape(A, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[ 9,  6],
        [ 1, 61],
        [68,  7]])>,
 <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
 array([[ 9,  1, 68],
        [ 6, 61,  7]])>,
 <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
 array([[ 9,  6,  1],
        [61, 68,  7]])>)

In [237]:
tf.matmul(tf.transpose(A), A)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[4706,  591],
       [ 591, 3806]])>

**The Dot Product**

Matrix multiplication is also called the dot product.

You can perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`

In [238]:
# Perform the dot producton X and Y (this requires X or Y to be transposed)

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[ 6,  3],
        [ 0, 16],
        [10,  9]])>,
 <tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[16,  1],
        [15,  8],
        [ 4,  5]])>)

In [239]:
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 99, 114,  39],
       [ 16, 128,  80],
       [169, 222,  85]])>

In [240]:
tf.tensordot(X, tf.reshape(Y, shape=(2, 3)), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[120,  18, 105],
       [128,  64,  80],
       [232,  46, 195]])>

In [241]:
# Check the value of Y, reshape Y and transposed Y
Y, tf.reshape(Y, shape=(2, 3)), tf.transpose(Y)

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[16,  1],
        [15,  8],
        [ 4,  5]])>,
 <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
 array([[16,  1, 15],
        [ 8,  4,  5]])>,
 <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
 array([[16, 15,  4],
        [ 1,  8,  5]])>)

### Changing the datatype of a tensor

In [242]:
B = tf.random.uniform(dtype=tf.float32, minval=0, maxval=10, shape=(2, 3))
B

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[9.583183 , 0.1680839, 3.156035 ],
       [1.6013157, 7.148702 , 7.892921 ]], dtype=float32)>

In [243]:
B.dtype

tf.float32

In [244]:
B

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[9.583183 , 0.1680839, 3.156035 ],
       [1.6013157, 7.148702 , 7.892921 ]], dtype=float32)>

In [245]:
tf.__version__

'2.15.0'

In [246]:
# Change from float32 to float16 (reduced precision)

B = tf.cast(B, dtype=tf.float16)
B.dtype

tf.float16

In [247]:
B

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[9.586 , 0.1681, 3.156 ],
       [1.602 , 7.15  , 7.895 ]], dtype=float16)>

In [248]:
# Change from float16 to int32

C = tf.cast(B, dtype=tf.int32)
C

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 0, 3],
       [1, 7, 7]], dtype=int32)>

### **Aggregating Tensors**

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [249]:
# Getting the absolute values

D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [250]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [251]:
E = tf.random.uniform(minval=-10, maxval=-1, shape=(3, 4), dtype=tf.int32)
E

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[-3, -6, -2, -7],
       [-5, -9, -2, -2],
       [-8, -7, -3, -7]], dtype=int32)>

In [252]:
tf.abs(E)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[3, 6, 2, 7],
       [5, 9, 2, 2],
       [8, 7, 3, 7]], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [253]:
# Create a random tensor with values between 0 and 100 of size 50

F = tf.constant(np.random.randint(0, 100, size=50), shape=(5, 10))
F

<tf.Tensor: shape=(5, 10), dtype=int64, numpy=
array([[91, 80, 73, 89, 55, 28, 58, 99, 89, 13],
       [80, 16,  6, 34, 13, 88, 50, 93, 62,  4],
       [99, 84, 59, 30, 88, 19, 53, 37, 20, 78],
       [26, 35, 97, 71, 64,  2, 97, 28, 48, 83],
       [ 7, 31, 84,  9, 41, 59, 99,  5, 74, 12]])>

In [254]:
F.shape, tf.size(F), F.ndim

(TensorShape([5, 10]), <tf.Tensor: shape=(), dtype=int32, numpy=50>, 2)

In [255]:
# Find the minimum

tf.reduce_min(F), tf.reduce_min(F).numpy()

(<tf.Tensor: shape=(), dtype=int64, numpy=2>, 2)

In [256]:
# Find the maximum

tf.reduce_max(F), tf.reduce_max(F).numpy()

(<tf.Tensor: shape=(), dtype=int64, numpy=99>, 99)

In [257]:
# Find the mean

tf.reduce_mean(F), tf.reduce_mean(F).numpy()

(<tf.Tensor: shape=(), dtype=int64, numpy=53>, 53)

In [258]:
# Find the sum

tf.reduce_sum(F), tf.reduce_sum(F).numpy()

(<tf.Tensor: shape=(), dtype=int64, numpy=2660>, 2660)

In [259]:
# Find the variance

np.var(F.numpy())

1017.0

In [260]:
F_float = tf.cast(F, dtype=tf.float32)
tf.math.reduce_variance(F_float), tf.math.reduce_variance(F_float).numpy()

(<tf.Tensor: shape=(), dtype=float32, numpy=1017.0>, 1017.0)

In [261]:
tf.math.reduce_std(F_float), tf.math.reduce_std(F_float).numpy()

(<tf.Tensor: shape=(), dtype=float32, numpy=31.890436>, 31.890436)

### **Using the `tensorflow_probability` library to use `tensorflow_probability.stats.variance()` to find the variance**

In [262]:
import tensorflow_probability as tfp

tfp.stats.variance(F)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([1369,  759,  992,  848,  618,  938,  478, 1380,  555, 1216])>

**Using the `tensorflow_probability` library to use `tensorflow_probability.stats.stddev()` to find the standard deviation**

In [263]:
tfp.stats.stddev(F_float)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([37.000538, 27.549229, 31.49222 , 29.124561, 24.862823, 30.629396,
       21.877842, 37.1462  , 23.559286, 34.876926], dtype=float32)>

In [264]:
G = tf.constant(np.random.randint(0, 100, size=20), shape=(1, 20))
G

<tf.Tensor: shape=(1, 20), dtype=int64, numpy=
array([[34, 30, 63, 93, 27, 91, 62, 95, 61, 92, 87, 51, 86, 39, 58, 80,
        80, 70, 78, 64]])>

In [265]:
G.shape, tf.size(G), G.ndim

(TensorShape([1, 20]), <tf.Tensor: shape=(), dtype=int32, numpy=20>, 2)

In [266]:
tf.reduce_min(G)

<tf.Tensor: shape=(), dtype=int64, numpy=27>

In [267]:
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [268]:
tf.reduce_mean(G)

<tf.Tensor: shape=(), dtype=int64, numpy=67>

In [269]:
tf.reduce_sum(G)

<tf.Tensor: shape=(), dtype=int64, numpy=1341>

In [270]:
np.var(G.numpy())

457.74749999999995

In [271]:
tf.math.reduce_variance(tf.cast(G, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=457.74747>

In [272]:
tfp.stats.variance(G)

<tf.Tensor: shape=(20,), dtype=int64, numpy=array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])>

In [273]:
tf.math.reduce_std((tf.cast(G, dtype=tf.float32)))

<tf.Tensor: shape=(), dtype=float32, numpy=21.395033>

In [274]:
np.std(G.numpy())

21.395034470642948

### Find the Positional Maximum and Minimum

In [275]:
# Create a new tensor for finding the positional minimum and maximum

tf.random.set_seed(42)

H = tf.random.uniform(shape=[50])
H

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [276]:
# Find the positional maximum

tf.argmax(H), np.argmax(H)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>, 42)

In [277]:
# Index on out largest value position
H[tf.argmax(H)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [278]:
tf.reduce_max(H)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [279]:
# Check for equality

assert H[tf.argmax(H)] == tf.reduce_max(H)

In [280]:
(H[tf.argmax(H)] == tf.reduce_max(H)).numpy()

True

In [281]:
# Find the positional minimum

tf.argmin(H), np.argmin(H)

(<tf.Tensor: shape=(), dtype=int64, numpy=16>, 16)

In [282]:
# Find the minimum uing the positional minimum index

H[tf.argmin(H)], (H[tf.argmin(H)]).numpy()

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>, 0.009463668)

### Squeezing a tensor

In [283]:
# Create a new tensor

tf.random.set_seed(42)

I = tf.constant(tf.random.uniform(shape=(1, 50)), shape=(1, 1, 1, 1, 50))
I

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [284]:
I.shape

TensorShape([1, 1, 1, 1, 50])

In [285]:
I_squeezed = tf.squeeze(I)
I_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [286]:
I_squeezed.shape

TensorShape([50])

## One-Hot Encoding Tensors

In [287]:
# Create a list of indices

some_list = [0, 1, 2, 3, 4]  # could be red, green, blue, purple, white

# One hot encode our list of indices

tf.one_hot(some_list, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [288]:
# Specify custom values for one hot encoding

tf.one_hot(some_list, depth=5, on_value="YES", off_value="NO")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'YES', b'NO', b'NO', b'NO', b'NO'],
       [b'NO', b'YES', b'NO', b'NO', b'NO'],
       [b'NO', b'NO', b'YES', b'NO', b'NO'],
       [b'NO', b'NO', b'NO', b'YES', b'NO'],
       [b'NO', b'NO', b'NO', b'NO', b'YES']], dtype=object)>

In [289]:
# One Hot encoding in Scikit-Learn

import numpy as np
from sklearn.preprocessing import OneHotEncoder

# Sample data
data = np.array([
    ['red'],
    ['green'],
    ['blue'],
    ['red'],
    ['green']
])

# Initialize OneHotEncoder
encoder = OneHotEncoder(sparse=False)

# Fit and transform the data
encoded_data = encoder.fit_transform(data)

# Display the encoded data
print(encoded_data)

# Optionally, get feature names
feature_names = encoder.get_feature_names_out(['color'])
print(feature_names)

# Inverse transform the encoded data to get original values
decoded_data = encoder.inverse_transform(encoded_data)

# Display the decoded data
print("Decoded Data:\n", decoded_data)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
['color_blue' 'color_green' 'color_red']
Decoded Data:
 [['red']
 ['green']
 ['blue']
 ['red']
 ['green']]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


### Math Functions

**Squaring, Log and Square Root**

In [290]:
J = tf.range(0, 10)
J

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [291]:
# Square

tf.square(J)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [292]:
# Square Root

tf.math.sqrt(tf.cast(J, dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.2360678,
       2.4494896, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [293]:
# Logarithm

tf.math.log(tf.cast(J, dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy

In [294]:
# Create a tensor directly from a numpy array

K = tf.constant(np.arange(1, 10 + 1), dtype=tf.float32)
K

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)>

In [295]:
K.numpy(), type(K.numpy())

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32),
 numpy.ndarray)

In [296]:
np.array(K), K.dtype

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32),
 tf.float32)

### Miscellaneous

In [297]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [298]:
!nvidia-smi

Fri May 31 17:54:03 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P0              30W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--